import {
  AbsoluteFill,
  Audio,
  Sequence,
  interpolate,
  spring,
  staticFile,
  useCurrentFrame,
  useVideoConfig,
} from 'remotion';
import {loadFont} from '@remotion/google-fonts/NotoSansTamil';
import script from './script.json';

const {fontFamily: tamilFont} = loadFont();
const SANS = 'Inter, -apple-system, "Helvetica Neue", Arial, sans-serif';
const ACCENT = '#5b9dff';
const N_INTRO = 3; // first N segments are the spoken introduction; the rest are voice samples

type Seg = {file: string; tamil: string; en: string; start: number; dur: number};

const FadeUp: React.FC<{at: number; y?: number; children: React.ReactNode}> = ({at, y = 22, children}) => {
  const frame = useCurrentFrame();
  const {fps} = useVideoConfig();
  const s = spring({frame: frame - at, fps, config: {damping: 200}});
  return <div style={{opacity: s, transform: `translateY(${interpolate(s, [0, 1], [y, 0])}px)`}}>{children}</div>;
};

const Segment: React.FC<{seg: Seg; index: number}> = ({seg, index}) => {
  const intro = index < N_INTRO;
  return (
    <Sequence from={seg.start} durationInFrames={seg.dur + 16}>
      <Audio src={staticFile(seg.file)} />
      <AbsoluteFill style={{justifyContent: 'center', alignItems: 'center', padding: 96}}>
        {!intro && (
          <FadeUp at={3}>
            <div style={{fontFamily: SANS, fontSize: 21, color: ACCENT, letterSpacing: 3, textTransform: 'uppercase', marginBottom: 26}}>
              {`Voice sample ${index - N_INTRO + 1}`}
            </div>
          </FadeUp>
        )}
        <FadeUp at={6}>
          <div style={{fontFamily: tamilFont, fontSize: 62, color: 'white', textAlign: 'center', lineHeight: 1.32, maxWidth: 1060, textWrap: 'balance'}}>
            {seg.tamil}
          </div>
        </FadeUp>
        <FadeUp at={13}>
          <div style={{fontFamily: SANS, fontSize: 29, color: '#9fb3c8', marginTop: 30, textAlign: 'center', maxWidth: 980, textWrap: 'balance'}}>
            {seg.en}
          </div>
        </FadeUp>
      </AbsoluteFill>
    </Sequence>
  );
};

type Show = {file: string; label: string; sub: string; start: number; dur: number};

const ShowcaseClip: React.FC<{show: Show}> = ({show}) => (
  <Sequence from={show.start} durationInFrames={show.dur + 16}>
    <Audio src={staticFile(show.file)} />
    <AbsoluteFill style={{justifyContent: 'center', alignItems: 'center', padding: 96}}>
      <FadeUp at={3}>
        <div style={{fontFamily: tamilFont, fontSize: 58, color: '#9fb3c8', textAlign: 'center', marginBottom: 34}}>
          {(script as {showcase_text: string}).showcase_text}
        </div>
      </FadeUp>
      <FadeUp at={6}>
        <div style={{fontFamily: SANS, fontSize: 64, color: 'white', fontWeight: 700, textAlign: 'center'}}>
          {show.label}
        </div>
      </FadeUp>
      <FadeUp at={11}>
        <div style={{fontFamily: SANS, fontSize: 28, color: ACCENT, marginTop: 18, letterSpacing: 1}}>
          {show.sub}
        </div>
      </FadeUp>
    </AbsoluteFill>
  </Sequence>
);

export const Intro: React.FC = () => {
  const frame = useCurrentFrame();
  const progress = Math.min(frame / script.total, 1);
  return (
    <AbsoluteFill style={{background: 'radial-gradient(120% 120% at 50% 0%, #16233a 0%, #0a0f1a 60%, #070a12 100%)'}}>
      {/* subtle background music across the whole video */}
      <Audio src={staticFile('music.wav')} volume={2.0} />

      {/* footer: progress bar + repo */}
      <AbsoluteFill style={{justifyContent: 'flex-end'}}>
        <div style={{height: 4, width: `${progress * 100}%`, background: ACCENT}} />
        <div style={{textAlign: 'center', fontFamily: SANS, fontSize: 20, color: '#5f7591', padding: '14px 0', letterSpacing: 1}}>
          github.com/ashwanthkumar/tamil-tts
        </div>
      </AbsoluteFill>

      {/* title card */}
      <Sequence durationInFrames={script.intro}>
        <AbsoluteFill style={{justifyContent: 'center', alignItems: 'center'}}>
          <FadeUp at={6}>
            <div style={{fontFamily: tamilFont, fontSize: 124, color: 'white', fontWeight: 700}}>தமிழ் TTS</div>
          </FadeUp>
          <FadeUp at={18}>
            <div style={{fontFamily: SANS, fontSize: 33, color: ACCENT, marginTop: 14}}>Tamil text-to-speech · MLX → ONNX</div>
          </FadeUp>
          <FadeUp at={30}>
            <div style={{fontFamily: SANS, fontSize: 22, color: '#9fb3c8', marginTop: 16}}>every voice below is generated by the model</div>
          </FadeUp>
        </AbsoluteFill>
      </Sequence>

      {(script.segments as Seg[]).map((seg, i) => (
        <Segment key={i} seg={seg} index={i} />
      ))}

      {/* v0.2 prosody-control showcase: title card + one line at different knob settings */}
      <Sequence
        from={(script as {showcase_title_start: number}).showcase_title_start}
        durationInFrames={(script as {showcase_title: number}).showcase_title}
      >
        <AbsoluteFill style={{justifyContent: 'center', alignItems: 'center'}}>
          <FadeUp at={6}>
            <div style={{fontFamily: SANS, fontSize: 21, color: ACCENT, letterSpacing: 3, textTransform: 'uppercase', marginBottom: 22}}>
              New in v0.2
            </div>
          </FadeUp>
          <FadeUp at={12}>
            <div style={{fontFamily: SANS, fontSize: 76, color: 'white', fontWeight: 700, textAlign: 'center'}}>Controllable prosody</div>
          </FadeUp>
          <FadeUp at={24}>
            <div style={{fontFamily: SANS, fontSize: 30, color: '#9fb3c8', marginTop: 18, textAlign: 'center'}}>
              the same line — adjust speed, pitch &amp; energy
            </div>
          </FadeUp>
        </AbsoluteFill>
      </Sequence>
      {((script as {showcase: Show[]}).showcase ?? []).map((show, i) => (
        <ShowcaseClip key={`show${i}`} show={show} />
      ))}

      {/* closing acknowledgment / thank-you (with model voice-over) */}
      <Sequence from={(script as {ack_start: number}).ack_start}>
        <Sequence from={(script as {ack_lead: number}).ack_lead}>
          <Audio src={staticFile((script as {ack_audio: string}).ack_audio)} />
        </Sequence>
        <AbsoluteFill style={{justifyContent: 'center', alignItems: 'center', padding: 100}}>
          <FadeUp at={4}>
            <div style={{fontFamily: tamilFont, fontSize: 100, color: 'white', fontWeight: 700}}>நன்றி</div>
          </FadeUp>
          <FadeUp at={14}>
            <div style={{fontFamily: SANS, fontSize: 31, color: '#cdd9e6', marginTop: 26, textAlign: 'center', maxWidth: 1040, lineHeight: 1.45}}>
              Built with the <b style={{color: 'white'}}>IndicTTS Tamil</b> corpus.
            </div>
          </FadeUp>
          <FadeUp at={26}>
            <div style={{fontFamily: SANS, fontSize: 27, color: '#9fb3c8', marginTop: 18, textAlign: 'center', maxWidth: 1040, lineHeight: 1.45}}>
              With gratitude to the <b style={{color: ACCENT}}>IIT&nbsp;Madras</b> Indic&nbsp;TTS team for sharing the dataset.
            </div>
          </FadeUp>
        </AbsoluteFill>
      </Sequence>
    </AbsoluteFill>
  );
};
